import i1 from '../src/Components/images/i1.jpg'
import i2 from '../src/Components/images/i2.jpg'
import i3 from '../src/Components/images/i3.jpg'
import i4 from '../src/Components/images/i4.jpg'
import i5 from '../src/Components/images/i5.jpg'

export const datas = [
    { name: 'Andrew Jain', username: "andrewjain", work: 'Data Scientist', img: i1, post: "React makes it painless to create interactive UIs. Design simple views for each state in your application, and React will efficiently update and render just the right components when your data changes.Declarative views make your code more predictable and easier to debug.Build encapsulated components that manage their own state, then compose them to make complex UIs.Since component logic is written in JavaScript instead of templates, you can easily pass rich data through your app and keep state out of the DOM." },
    { name: 'Miss Chainy', username: "chainythoma", work: 'Software Engineer', img: i2, post: "This is the third installment in a series on leveraging pydantic for Django-based projects. Part 1 focused on pydantic’s use of Python type hints to streamline Django settings management; part 2 built an app on this concept with Docker and conda to show how to align development and production environments.Deploying source code—and redeploying after updates—can be a frustrating process that leaves you brokenhearted. After so many bad relationships with other deployment platforms, I feel lucky to have found lasting happiness with Django and Heroku. I want to share the secrets of my success through a carefully curated example.We want to deploy our Django application and ensure it is easy and secure by default. Heroku provides a no-stress relationship with our application platform by combining efficiency and security." },
    { name: 'Thoms Vikram', username: "vikramthomas21", work: 'Full Stack Developer', img: i3, post: "With Heroku installed, creating our app is the initial step toward deploying our source code. This app not only points to our source code repository, but also enumerates which add-ons we need.A critical note about Heroku deployment is that every application must have a unique name for every person using Heroku. Therefore, we cannot use a single example name while going through these steps. Please pick a name that makes you happy and plug that into the instruction block throughout this tutorial. Our screenshots will list the app name as hello-visitor, but as you follow along, your uniquely chosen name will appear in those locations instead." },
    { name: 'Jiny William', username: "jinywilliam2", work: 'MERN Stack', img: i4, post: "With Heroku installed, creating our app is the initial step toward deploying our source code. This app not only points to our source code repository, but also enumerates which add-ons we need.A critical note about Heroku deployment is that every application must have a unique name for every person using Heroku. Therefore, we cannot use a single example name while going through these steps. Please pick a name that makes you happy and plug that into the instruction block throughout this tutorial. Our screenshots will list the app name as hello-visitor, but as you follow along, your uniquely chosen name will appear in those locations instead." },
    { name: 'Alex Wang', username: "alexwang", work: 'Ml Engineer', img: i5, post: "With Heroku installed, creating our app is the initial step toward deploying our source code. This app not only points to our source code repository, but also enumerates which add-ons we need.A critical note about Heroku deployment is that every application must have a unique name for every person using Heroku. Therefore, we cannot use a single example name while going through these steps. Please pick a name that makes you happy and plug that into the instruction block throughout this tutorial. Our screenshots will list the app name as hello-visitor, but as you follow along, your uniquely chosen name will appear in those locations instead." },
    { name: 'Alex Wang', username: "alexwang", work: 'Ml Engineer', img: i5, post: "With Heroku installed, creating our app is the initial step toward deploying our source code. This app not only points to our source code repository, but also enumerates which add-ons we need.A critical note about Heroku deployment is that every application must have a unique name for every person using Heroku. Therefore, we cannot use a single example name while going through these steps. Please pick a name that makes you happy and plug that into the instruction block throughout this tutorial. Our screenshots will list the app name as hello-visitor, but as you follow along, your uniquely chosen name will appear in those locations instead." }

]